import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider fallbackRedirectUrl="/dashboard">
      <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Toaster></Toaster>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
